#ssd 0 to 9 digit display
import RPi.GPIO as GPIO
import time
GPIO.Setmode(GPIO.BCM)
GPIO.Setwornings(False)
time sleep(1)
a=14
b=15
c=18
d=23
e=24
f=25
g=8
dp=7
GPIO.Setup(a,GPIO.OUT)
GPIO.Setup(b,GPIO.OUT)
GPIO.Setup(c,GPIO.OUT)
GPIO.Setup(d,GPIO.OUT)
GPIO.Setup(e,GPIO.OUT)
GPIO.Setup(f,GPIO.OUT)
GPIO.Setup(g,GPIO.OUT)
GPIO.Setup(dp,GPIO.OUT)
while True:
    #display 0
    GPIO.Output(a,False)
    GPIO.Output(b,False)
    GPIO.Output(c,False)
    GPIO.Output(d,False)
    GPIO.Output(e,False)
    GPIO.Output(f,False)
    GPIO.Output(g,True)
    GPIO.Output(dp,True)
    time.sleep(1)
    #display 1
    GPIO.Output(a,True)
    GPIO.Output(b,False)
    GPIO.Output(c,False)
    GPIO.Output(d,True)
    GPIO.Output(e,True)
    GPIO.Output(f,True)
    GPIO.Output(g,True)
    GPIO.Output(dp,True)
    time.sleep(1)
    #display 2
    GPIO.Output(a,False)
    GPIO.Output(b,False)
    GPIO.Output(c,True)
    GPIO.Output(d,False)
    GPIO.Output(e,False)
    GPIO.Output(f,True)
    GPIO.Output(g,False)
    GPIO.Output(dp,True)
    time.sleep(1)
    #display 3
    GPIO.Output(a,False)
    GPIO.Output(b,False)
    GPIO.Output(c,False)
    GPIO.Output(d,False)
    GPIO.Output(e,True)
    GPIO.Output(f,True)
    GPIO.Output(g,False)
    GPIO.Output(dp,True)
    time.sleep(1)
    #display 4
    GPIO.Output(a,True)
    GPIO.Output(b,False)
    GPIO.Output(c,False)
    GPIO.Output(d,True)
    GPIO.Output(e,True)
    GPIO.Output(f,False)
    GPIO.Output(g,False)
    GPIO.Output(dp,True)
    time.sleep(1)
    #display 5
    GPIO.Output(a,False)
    GPIO.Output(b,True)
    GPIO.Output(c,False)
    GPIO.Output(d,False)
    GPIO.Output(e,True)
    GPIO.Output(f,False)
    GPIO.Output(g,False)
    GPIO.Output(dp,True)
    time.sleep(1)
    #display 6
    GPIO.Output(a,False)
    GPIO.Output(b,True)
    GPIO.Output(c,False)
    GPIO.Output(d,False)
    GPIO.Output(e,False)
    GPIO.Output(f,False)
    GPIO.Output(g,False)
    GPIO.Output(dp,True)
    time.sleep(1)
    #display 7
    GPIO.Output(a,False)
    GPIO.Output(b,False)
    GPIO.Output(c,False)
    GPIO.Output(d,True)
    GPIO.Output(e,True)
    GPIO.Output(f,True)
    GPIO.Output(g,True)
    GPIO.Output(dp,True)
    time.sleep(1)
    #display 8
    GPIO.Output(a,False)
    GPIO.Output(b,False)
    GPIO.Output(c,False)
    GPIO.Output(d,False)
    GPIO.Output(e,False)
    GPIO.Output(f,False)
    GPIO.Output(g,False)
    GPIO.Output(dp,True)
    time.sleep(1)
    #display 9
    GPIO.Output(a,False)
    GPIO.Output(b,False)
    GPIO.Output(c,False)
    GPIO.Output(d,False)
    GPIO.Output(e,True)
    GPIO.Output(f,False)
    GPIO.Output(g,False)
    GPIO.Output(dp,True)
